var config = {
    hostApi: "https://12.trendndaily.com",
    eventApi: "https://12.trendndaily.com",
    isTest : 0,
    isCanary : "0",
    serverEnv : "prod",
    hostApiV1: "https://12.trendndaily.com",
    anuraInstanceId: 3508576879,
    journayaCampaignId: '188b0326-cfd8-39ef-5937-f63cdd569613',
    enableAnuraSpamCheck: true,
    site_id: 29,
    contentData: {"content_id":1509,"site_id":29,"key_data":"TnD1000Cashapp","config_data":null},
    dimensionConfig: null};
var session_id = '9c807f2c-c5bc-4439-9ac3-3afea7412702';
var cookie_id = '7db2b335-4d88-40aa-8442-e48b61b720b9';
var campaign_data = {"campaignId":"zqkxq-1682","flowHash":"72574b1950865f24cf4d7c02e9a30fde","surveyV2":true,"surveyVersion":5,"hospostPrepingComplete":false,"surveyQuestionCap":null,"surveyQuestionCapRoot":null,"surveySkipQuestionCap":null,"profanityBlockingEnabled":true};
var flowData = {"next_page":"register-step1","flow_page_slug":"lander","page_path":"flow\/lander\/tnd-lander-base-v5.html","flow_page_name":"lander with cta processing","default_page":"flow\/lander\/tnd-lander-base-v5.html","page":"flow\/lander\/tnd-lander-base-v5.html","is_dynamic_template":1,"api_path":"survey\/register-user","experiment_id":null,"page_id":2246,"experiment_name":null,"experiment_slug":null};
var flowPages = ["flow\/lander\/tnd-lander-base-v5.html","flow\/register\/tnd-reg-step1-bv3.html","flow\/register\/tnd-regstep2-survey-bv6.html","flow\/linkout\/tnd-linkout-base-v1.html","flow\/fulfillment\/tnd-fulfillment-v1.html"];
var fallbackLinkoutOffer = [];
var requestData = {"cid":"zqkxq-1682","t1":"3554","t2":null,"t3":"6709ed5b4f222c00015a84c1","t4":"u100358","t5":null,"t8":"TnD1000Cashapp","transaction_id":"102777ea6529dd4f3ceb6a05861db1","isr":"true","sessionid":"4303343f-d4bc-4043-8bb6-ac5050129fd1","surveyv2":true};
var tracking = null;
var expsettings = {"linkout":{"open":3}};
var userDetail = {};
var offerwall = {};
var offerwallDynamicConfig = [];
var postbackPixelData = [{"url":"https:\/\/imtrk.go2cloud.org\/aff_lsr?&transaction_id={transaction_id}","page":"register-step1","method":"conversion","blockId":null,"affiliate":"hasOffers","pixelSource":"server","eventDetails":null,"mandatoryFields":["transaction_id"]}];
var customData = {"creativeDomain":"creatives.trendndaily.com","googleCaptchaKey":"6Ld-4zQpAAAAABmZ7KsYy2-mjK5yPdPXg46aOIyL","onetrustFooterLink":"https:\/\/privacyportal.onetrust.com\/webform\/9778300d-e8e2-4455-a4ff-488f60a54302\/92aba22c-ab14-4a3f-8e85-e1fff7ac6c7e","gameplay":null,"autoPrepop":null,"tValue":"pubgiveawaypehdup,TnD1000Cashapp","tValueParam":"t8","tValueExist":true,"tValueForced":true,"surveyMacroName":"sweeps","domainSlug":null,"enableNotifyAi":false,"notifyAiKey":null,"lander_disclaimer":"By clicking '{{ctaText}}', I agree to receive emails from TrendnDaily and its partners. I also agree to the <a href='https:\/\/trendndaily.com\/privacy-policy.html' target='_blank'>Privacy Policy<\/a> which includes details on the collection and use of my personal data, the <a href='https:\/\/trendndaily.com\/terms-and-conditions.html' target='_blank'>Terms of Use<\/a> which includes a mandatory arbitration provision & the<a href= 'https:\/\/trendndaily.com\/official-rules.html' target='_blank'> Official Rules <\/a> which govern this promotion.","optOutUrl":"https:\/\/trendndaily.com\/tnd-spii-v1.html","gamePlayTValue":"t8","pushnami_prompt_loc":"lander","user_profile":{"emailAddress":null},"enablePushNami":true,"isSubdomain":true,"labelName":"TrendnDaily","isSpam":true,"traffic_source_name":"Adstart Media","traffic_source_id":903,"offerVisibilityTimeOW":null,"offerVisibilityThresholdOW":null};
var gtmEvents = {"com|section|registration":"RegistrationSectionComplete","registrationsectioncomplete":"RegistrationSectionComplete","com|section|expressregistration":"ExpressRegistrationSectionComplete","expressregistrationsectioncomplete":"ExpressRegistrationSectionComplete","click|change|partial-tcpa-optin":"TCPAOptin","click|change|tcpa-optin":"TCPAOptin","tcpaoptin":"TCPAOptin","com|section|hostandpost":"HostPostSectionComplete","click|block|linkout":"LinkoutOfferClick","linkoutjobofferclick":"LinkoutJobOfferClick"};
var pushnamiUrl = "https:\/\/api.pushnami.com\/scripts\/v1\/pushnami-adv\/65677192f0b3320013d33ecb";
var pushnamiRedirectTimeout = 5000;

var phoneAreaListRaw = [
"205",
"251",
"256",
"334",
"938",
"907",
"480",
"520",
"602",
"623",
"928",
"479",
"501",
"870",
"209",
"213",
"279",
"310",
"323",
"408",
"415",
"424",
"442",
"510",
"530",
"559",
"562",
"619",
"626",
"628",
"650",
"657",
"661",
"669",
"707",
"714",
"747",
"760",
"805",
"818",
"820",
"831",
"858",
"909",
"916",
"925",
"949",
"951",
"204",
"226",
"236",
"249",
"250",
"289",
"306",
"343",
"365",
"367",
"403",
"416",
"418",
"431",
"437",
"438",
"450",
"506",
"514",
"519",
"548",
"579",
"581",
"587",
"604",
"613",
"639",
"647",
"705",
"709",
"778",
"780",
"782",
"807",
"819",
"825",
"867",
"873",
"902",
"905",
"303",
"719",
"720",
"970",
"203",
"475",
"860",
"959",
"302",
"239",
"305",
"321",
"352",
"386",
"407",
"561",
"727",
"754",
"772",
"786",
"813",
"850",
"863",
"904",
"941",
"954",
"229",
"404",
"470",
"478",
"678",
"706",
"762",
"770",
"912",
"808",
"208",
"986",
"217",
"224",
"309",
"312",
"331",
"618",
"630",
"708",
"773",
"779",
"815",
"847",
"872",
"219",
"260",
"317",
"463",
"574",
"765",
"812",
"930",
"319",
"515",
"563",
"641",
"712",
"316",
"620",
"785",
"913",
"270",
"364",
"502",
"606",
"859",
"225",
"318",
"337",
"504",
"985",
"207",
"240",
"301",
"410",
"443",
"667",
"339",
"351",
"413",
"508",
"617",
"774",
"781",
"857",
"978",
"231",
"248",
"269",
"313",
"517",
"586",
"616",
"734",
"810",
"906",
"947",
"989",
"218",
"320",
"507",
"612",
"651",
"763",
"952",
"228",
"601",
"662",
"769",
"314",
"417",
"573",
"636",
"660",
"816",
"406",
"308",
"402",
"531",
"702",
"725",
"775",
"603",
"201",
"551",
"609",
"640",
"732",
"848",
"856",
"862",
"908",
"973",
"505",
"575",
"212",
"315",
"332",
"347",
"516",
"518",
"585",
"607",
"631",
"646",
"680",
"716",
"718",
"838",
"845",
"914",
"917",
"929",
"934",
"252",
"336",
"704",
"743",
"828",
"910",
"919",
"980",
"984",
"701",
"216",
"220",
"234",
"330",
"380",
"419",
"440",
"513",
"567",
"614",
"740",
"937",
"405",
"539",
"580",
"918",
"458",
"503",
"541",
"971",
"215",
"223",
"267",
"272",
"412",
"445",
"484",
"570",
"610",
"717",
"724",
"814",
"878",
"401",
"803",
"843",
"854",
"864",
"605",
"423",
"615",
"629",
"731",
"865",
"901",
"931",
"340",
"670",
"671",
"684",
"787",
"939",
"210",
"214",
"254",
"281",
"325",
"346",
"361",
"409",
"430",
"432",
"469",
"512",
"682",
"713",
"726",
"737",
"806",
"817",
"830",
"832",
"903",
"915",
"936",
"940",
"956",
"972",
"979",
"385",
"435",
"801",
"802",
"276",
"434",
"540",
"571",
"703",
"757",
"804",
"206",
"253",
"360",
"425",
"509",
"564",
"202",
"304",
"681",
"262",
"414",
"534",
"608",
"715",
"920",
"307",
];
var stateListRaw = [
{ code: "AL", state: "Alabama" },
{ code: "AK", state: "Alaska" },
{ code: "AA", state: "APO - AA" },
{ code: "AE", state: "APO - AE" },
{ code: "AP", state: "APO - AP" },
{ code: "AZ", state: "Arizona" },
{ code: "AR", state: "Arkansas" },
{ code: "CA", state: "California" },
{ code: "CO", state: "Colorado" },
{ code: "CT", state: "Connecticut" },
{ code: "DE", state: "Delaware" },
{ code: "DC", state: "District of Columbia" },
{ code: "FL", state: "Florida" },
{ code: "GA", state: "Georgia" },
{ code: "HI", state: "Hawaii" },
{ code: "ID", state: "Idaho" },
{ code: "IL", state: "Illinois" },
{ code: "IN", state: "Indiana" },
{ code: "IA", state: "Iowa" },
{ code: "KS", state: "Kansas" },
{ code: "KY", state: "Kentucky" },
{ code: "LA", state: "Louisiana" },
{ code: "ME", state: "Maine" },
{ code: "MD", state: "Maryland" },
{ code: "MA", state: "Massachusetts" },
{ code: "MI", state: "Michigan" },
{ code: "MN", state: "Minnesota" },
{ code: "MS", state: "Mississippi" },
{ code: "MO", state: "Missouri" },
{ code: "MT", state: "Montana" },
{ code: "NE", state: "Nebraska" },
{ code: "NV", state: "Nevada" },
{ code: "NH", state: "New Hampshire" },
{ code: "NJ", state: "New Jersey" },
{ code: "NM", state: "New Mexico" },
{ code: "NY", state: "New York" },
{ code: "NC", state: "North Carolina" },
{ code: "ND", state: "North Dakota" },
{ code: "OH", state: "Ohio" },
{ code: "OK", state: "Oklahoma" },
{ code: "OR", state: "Oregon" },
{ code: "PA", state: "Pennsylvania" },
{ code: "RI", state: "Rhode Island" },
{ code: "SC", state: "South Carolina" },
{ code: "SD", state: "South Dakota" },
{ code: "TN", state: "Tennessee" },
{ code: "TX", state: "Texas" },
{ code: "UT", state: "Utah" },
{ code: "VT", state: "Vermont" },
{ code: "VA", state: "Virginia" },
{ code: "WA", state: "Washington" },
{ code: "WV", state: "West Virginia" },
{ code: "WI", state: "Wisconsin" },
{ code: "WY", state: "Wyoming" },
{ code: "AS", state: "American Samoa" },
{ code: "FM", state: "Chuuk" },
{ code: "GU", state: "Guam" },
{ code: "MH", state: "Majuro" },
{ code: "MP", state: "Mariana Islands" },
{ code: "PR", state: "Puerto Rico" },
{ code: "VI", state: "Virgin Islands" }
];
var colorCode = {
pendingInputColor: "#778899",
completeInputColor: "#001122",
};
var PIIMapping = {
'emailAddress': 'emailAddress',
'email': 'emailAddress',
'mail': 'emailAddress',
'emailaddress': 'emailAddress',
'userFname': 'userFname',
'name': 'userFname',
'first_name': 'userFname',
'f_name': 'userFname',
'fname': 'userFname',
'first': 'userFname',
'userLname': 'userLname',
'lname': 'userLname',
'last_name': 'userLname',
'lastname': 'userLname',
'last': 'userLname',
'gendervalue1': 'gendervalue1',
'gender': 'gendervalue1',
'gen': 'gendervalue1',
'userAddress': 'userAddress',
'address': 'userAddress',
'street_address': 'userAddress',
'address1': 'userAddress',
'address_1': 'userAddress',
'cityName': 'cityName',
'city': 'cityName',
'stateName': 'stateName',
'state': 'stateName',
'zipcode': 'zipcode',
'zip': 'zipcode',
'countryName': 'countryName',
'country': 'countryName',
'countryCode': 'countryCode',
'country_code': 'countryCode',
'country_code': 'countryCode',
'mobile': 'mobile',
'phone': 'mobile',
'dobdate': 'dobdate',
'date': 'dobdate',
'birthdate': 'dobdate',
'dobmonth': 'dobmonth',
'birthmonth': 'dobmonth',
'month': 'dobmonth',
'dobyear': 'dobyear',
'year': 'dobyear',
'birthyear': 'dobyear',
'transaction_id': 'transaction_id',
't6':'t6',
't1':'t1',
't2':'t2',
't3':'t3',
't4':'t4',
't5':'t5',
't7':'t7',
't8':'t8'
};

var whitelisted_words = ["big bastard mountain"];

var grey_words = ["hell","god","poon","wang","pawn","bum","nob","spac","cipa","yed","lolita","4r5e","5h1t","5hit","a55","anal","anus","ar5e","arrse","ass","asses","asshole","assholes","asswhole","a_s_s","b!tch","b00bs","b17ch","b1tch","ballbag","balls","ballsack","bastard","beastial","beastiality","bellend","bestial","bestiality","bi+ch","bitcher","bitchers","bitches","bitchin","bitching","bloody","blowjob","blowjobs","boiolas","bollok","boner","boob","boobs","booobs","boooobs","booooobs","booooooobs","breasts","buceta","bugger","butt","butthole","buttmuch","buttplug","c0ck","c0cksucker","cawk","chink","cl1t","clitoris","clits","cnut","cock-sucker","cockface","cockhead","cockmunch","cockmuncher","cocks","cocksuck","cocksucked","cocksucking","cocksucks","cocksuka","cocksukka","cok","cokmuncher","coksucka","coon","crap","cum","cummer","cumming","cums","cumshot","cunilingus","cunillingus","cunnilingus","cuntlick","cuntlicker","cuntlicking","cunts","cyalis","d1ck","dickhead","dildo","dildos","dink","dinks","dirsa","dlck","doggin","dogging","donkeyribber","doosh","duche","ejaculate","ejaculated","ejaculates","ejaculating","ejaculatings","ejaculation","ejakulate","f u c k","f u c k e r","f4nny","fagging","faggitt","faggot","faggs","fagot","fagots","fags","fanny","fannyflaps","fanyy","fatass","fcuk","fcuker","fcuking","feck","fecker","felching","fellate","fellatio","flange","fook","fooker","fudgepacker","fux","fux0r","f_u_c_k","gangbang","gangbanged","gangbangs","gaysex","goatse","god-dam","goddamn","goddamned","hardcoresex","heshe","hoar","hoare","homo","hore","horniest","horny","hotsex","jack-off","jackoff","jap","jerk-off","jism","jiz","jizm","jizz","kawk","knobead","knobed","knobend","knobhead","knobjocky","knobjokey","kock","kondum","kondums","kum","kummer","kumming","kums","kunilingus","l3i+ch","l3itch","labia","lust","lusting","m0f0","m0fo","m45terbate","ma5terb8","ma5terbate","masochist","master-bate","masterb8","masterbat","masterbat3","masterbate","masterbation","masterbations","masturbate","mo-fo","mof0","mofo","muff","mutha","muthafecker","muther","n1gga","n1gger","nazi","nigg3r","nigg4h","nigga","niggah","niggas","niggaz","niggers","nob jokey","nobhead","nobjocky","nobjokey","numbnuts","nutsack","orgasim","orgasims","orgasm","orgasms","p0rn","pecker","penis","phonesex","phuked","phuking","phukked","phukking","phuks","phuq","pimpis","pissed","pisser","pissers","pisses","pissflaps","pissin","pissing","pissoff","poop","porn","porno","pornography","pornos","prick","pricks","pron","pube","pusse","pussi","pussies","pussy","pussys","rectum","retard","rimjaw","rimming","s hit","s.o.b.","sadist","schlong","screwing","scroat","scrote","scrotum","semen","sex","sh!+","sh1t","shag","shagger","shaggin","shagging","shemale","shi+","shitdick","shite","shited","shitey","shitfull","shithead","shiting","shitings","shits","shitted","shitter","shitters","shitting","shittings","skank","slut","sluts","smegma","smut","snatch","son-of-a-bitch","spunk","s_h_i_t","t1tt1e5","t1tties","teets","teez","testical","tit","tits","tittie5","titties","tittywank","titwank","tosser","turd","tw4t","twat","twathead","twatty","twunt","twunter","v14gra","v1gra","vagina","viagra","vulva","w00se","wanker","wanky","whoar","whore","willies","willy","xrated","xxx","2g1c","2 girls 1 cup","acrotomophilia","alabama hot pocket","alaskan pipeline","anilingus","apeshit","arsehole","assmunch","auto erotic","autoerotic","babeland","baby batter","baby juice","ball gag","ball gravy","ball kicking","ball licking","ball sack","ball sucking","bangbros","bangbus","bareback","barely legal","barenaked","bastardo","bastinado","bbw","bdsm","beaner","beaners","beaver cleaver","beaver lips","big black","big breasts","big knockers","big tits","bimbos","birdlock","black cock","blonde action","blonde on blonde action","blow your load","blue waffle","blumpkin","bollocks","bondage","booty call","brown showers","brunette action","bukkake","bulldyke","bullet vibe","bullshit","bung hole","bunghole","busty","buttcheeks","camel toe","camgirl","camslut","camwhore","carpetmuncher","chocolate rosebuds","cialis","circlejerk","cleveland steamer","clover clamps","coprolagnia","coprophilia","cornhole","coons","creampie","cumshots","darkie","date rape","daterape","deep throat","deepthroat","dendrophilia","dingleberry","dingleberries","dirty pillows","dirty sanchez","doggie style","doggiestyle","doggy style","doggystyle","dog style","dolcett","domination","dominatrix","dommes","donkey punch","double dong","double penetration","dp action","dry hump","dvda","eat my ass","ecchi","erotic","erotism","escort","eunuch","fecal","felch","feltch","female squirting","femdom","figging","fingerbang","fingering","fisting","foot fetish","footjob","frotting","futanari","gang bang","gay sex","genitals","giant cock","girl on","girl on top","girls gone wild","goatcx","god damn","gokkun","golden shower","goodpoop","goo girl","goregasm","grope","group sex","g-spot","guro","hand job","handjob","hard core","hardcore","hentai","homoerotic","honkey","hooker","hot carl","hot chick","how to kill","how to murder","huge fat","humping","incest","intercourse","jack off","jail bait","jailbait","jelly donut","jerk off","jigaboo","jiggaboo","jiggerboo","juggs","kike","kinbaku","kinkster","kinky","knobbing","leather restraint","leather straight jacket","lemon party","livesex","lovemaking","make me come","male squirting","masturbating","masturbation","menage a trois","milf","missionary position","mong","mound of venus","mr hands","muff diver","muffdiving","nambla","nawashi","negro","neonazi","nig nog","nimphomania","nipple","nipples","nsfw","nsfw images","nude","nudity","nutten","nympho","nymphomania","octopussy","omorashi","one cup two girls","one guy one jar","orgy","paedophile","paki","panties","panty","pedobear","pedophile","pegging","phone sex","piece of shit","pikey","piss pig","pisspig","playboy","pleasure chest","pole smoker","ponyplay","poof","poontang","punany","poop chute","poopchute","prince albert piercing","pthc","pubes","queaf","quim","raghead","raging boner","rape","raped","raping","rapist","reverse cowgirl","rimjob","rosy palm","rosy palm and her 5 sisters","rusty trombone","sadism","santorum","scat","scissoring","sexcam","sexo","sexy","sexual","sexually","sexuality","shaved beaver","shaved pussy","shibari","shitblimp","shota","shrimping","skeet","slanteye","s&m","snowballing","sodomize","sodomy","spastic","spic","splooge","splooge moose","spooge","spread legs","strap on","strapon","strappado","strip club","style doggy","suck","sucks","suicide girls","sultry women","swastika","swinger","tainted love","taste my","tea bagging","threesome","throating","thumbzilla","tied up","tight white","titty","tongue in a","topless","towelhead","tranny","tribadism","tub girl","tubgirl","tushy","twink","twinkie","two girls one cup","undressing","upskirt","urethra play","urophilia","venus mound","vibrator","violet wand","vorarephilia","voyeur","voyeurweb","voyuer","wet dream","white power","worldsex","wrapping men","wrinkled starfish","yaoi","yellow showers","yiffy","zoophilia","ahole","ash0le","ash0les","asholes","ass monkey","assface","assh0le","assh0lez","assholz","asswipe","azzhole","bassterds","bastards","bastardz","basterds","basterdz","biatch","blow job","boffing","buttwipe","c0cks","c0k","carpet muncher","cawks","clit","cnts","cntz","cock-head","cocksucker","cuntz","dild0","dild0s","dilld0","dilld0s","dominatricks","dominatrics","enema","fag1t","faget","fagg1t","faggit","fagg0t","fagit","fagz","faig","faigs","fart","flipping the bird","fudge packer","g00k","god-damned","h00r","h0ar","h0re","hells","hoor","hoore","japs","jisim","jiss","knobs","knobz","kunt","kunts","kuntz","lezzian","lipshits","lipshitz","masokist","massterbait","masstrbait","masstrbate","masterbaiter","masterbates","n1gr","nastt","nigger;","nigur;","niiger;","niigr;","orafis","orgasim;","orgasum","oriface","orifice","orifiss","packi","packie","packy","pakie","paky","peeenus","peeenusss","peenus","peinus","pen1s","penas","penis-breath","penus","penuus","phuc","phuck","phuk","phuker","phukker","polac","polack","polak","poonani","pr1c","pr1ck","pr1k","pussee","puuke","puuker","qweir","recktum","scank","sh1ter","sh1ts","sh1tter","sh1tz","shitty","shity","shitz","shyt","shyte","shytty","shyty","skanck","skankee","skankey","skanks","skanky","slag","slutty","slutz","va1jina","vag1na","vagiina","vaj1na","vajina","vullva","w0p","wh00r","wh0re","b!+ch","arschloch","damn","dyke","shit","@$$","amcik","andskota","arse","assrammer","ayir","bi7ch","bitch","bollock","butt-pirate","cabron","cazzo","chraa","chuj","cock","cunt","d4mn","daygo","dego","dick","dike","dupa","dziwka","ejackulate","ekrem","ekto","enculer","faen","fag","fanculo","feces","feg","felcher","ficken","fitt","flikker","foreskin","fotze","fu(","futkretzn","gook","guiena","h0r","h4x0r","helvete","hoer","huevon","hui","injun","kanker","klootzak","kraut","knulle","kuk","kuksuger","kurac","kurwa","kusi","kyrpa","lesbo","mamhoon","masturbat","merd","mibun","monkleigh","mouliewop","muie","mulkku","muschi","nazis","nepesaurio","nigger","orospu","paska","perse","picka","pierdol","pillu","pimmel","piss","pizda","poontsee","pr0n","preteen","pula","pule","puta","puto","qahbeh","queef","rautenberg","schaffer","scheiss","schlampe","schmuck","screw","sh!t","sharmuta","sharmute","shipal","shiz","skribz","skurwysyn","sphencter","spierdalaj","suka","b00b","testicle","titt","vittu","wank","wetback","wichser","wop","zabourah"];

var blacklisted_words = ["ass-fucker","assfucker","assfukka","bunny fucker","cyberfuc","cyberfuck","cyberfucked","cyberfucker","cyberfuckers","cyberfucking","dog-fucker","fannyfucker","fingerfuck","fingerfucked","fingerfucker","fingerfuckers","fingerfucking","fingerfucks","fistfuck","fistfucked","fistfucker","fistfuckers","fistfucking","fistfuckings","fistfucks","fuck","fucka","fucked","fucker","fuckers","fuckhead","fuckheads","fuckin","fucking","fuckings","fuckingshitmotherfucker","fuckme","fucks","fuckwhit","fuckwit","fuker","fuks","fukwhit","fukwit","mothafuck","mothafucka","mothafuckas","mothafuckaz","mothafucked","mothafucker","mothafuckers","mothafuckin","mothafucking","mothafuckings","mothafucks","motherfuck","motherfucked","motherfucker","motherfuckers","motherfuckin","motherfucking","motherfuckings","motherfuckka","motherfucks","muthafuckker","mutherfucker","penisfucker","pigfucker","shitfuck","titfuck","tittiefucker","tittyfuck","clusterfuck","fuck buttons","fucktards","fukah","fuken","fukin","fukk","fukkah","fukken","fukker","fukkin","motha fucker","motha fuker","motha fukkah","motha fukker","mother fucker","mother fukah","mother fuker","mother fukkah","mother fukker","mother-fucker","mutha fucker","mutha fukah","mutha fuker","mutha fukkah","mutha fukker","fuk"];

var campaign_config = {"tracking":null,"BypassDNC":false,"offerWall":null,"targetEpc":0.75,"enablePush":false,"payout_type":null,"tValueParam":"t8","costPerClick":null,"dripsOfferId":"s364","onoDoNotSend":{"sms":[],"email":["cmt"]},"targetMargin":10,"onoCidCapping":null,"scrubSpamUser":0,"abexperimentv2":true,"enableJournaya":true,"enablePushNami":true,"gamePlayTValue":null,"isDripsEnabled":false,"sweepsGameInfo":{"isEnabled":false},"tValueFallback":"TnD1000Cashapp","anuraInstanceId":"3508576879","automaticMargin":{"enabled":true,"algoType":"bucket","algoVersion":"strategy-bucket","targetMargin":8,"sourceVariable":"t1"},"enableAnuraSpam":true,"enableCanaryAMM":false,"enableYieldCost":false,"balanceTargetEpc":false,"emailDupFlowFlag":false,"enableEncryption":true,"enableEntryOffer":false,"isBucketOverride":false,"spamUserRedirect":1,"xverifyEmailable":[{"op":"in","key":"xverify.status","value":["risky","invalid"],"action":"risky"}],"dripsProjectToken":1,"enableGenericRoas":false,"leadQualityConfig":[{"RedirectTo":"403","LeadsDoNotPost":true,"selectedFields":["LeadsDoNotPostLogActivate","LeadsDoNotPost","RedirectTo","AMMDoNotFireConversion","AMMDoNotFireConversionLogActivate","AMMDoNotCreditTxnIDLogActivate","AMMDoNotCreditTxnID"],"AMMDoNotCreditTxnID":true,"LeadQualityExpression":"lead_score_v2 >=6","AMMDoNotFireConversion":true,"LeadsDoNotPostLogActivate":false,"AMMDoNotCreditTxnIDLogActivate":false,"AMMDoNotFireConversionLogActivate":false}],"logInvalidAddress":false,"logOnoUnsubStatus":false,"postbackPixelData":[{"url":"https:\/\/imtrk.go2cloud.org\/aff_lsr?&transaction_id={transaction_id}","page":"register-step1","method":"conversion","blockId":null,"affiliate":"hasOffers","pixelSource":"server","eventDetails":null,"mandatoryFields":["transaction_id"]}],"BypassXverifyEmail":false,"BypassXverifyPhone":true,"applyScalingFactor":false,"enableSentryClient":true,"externalLeadConfig":null,"yieldCutoffMinutes":30,"blockInvalidAddress":false,"bypassLiveOnoUnsubs":true,"enablePushNamiRatio":null,"enableSessionBucket":false,"enableVisitorBucket":false,"increaseYieldVolume":false,"isCrossSellCampaign":false,"is_generic_campaign":false,"rpuCorrectionFactor":10,"scrambleConversions":false,"XverifyLogPhoneCheck":false,"enableAnuraSpamCheck":true,"excludeHasoffersCost":false,"minimumPrepingAccept":75,"enableGoogleOptimizer":false,"enableHardcodedMPList":false,"enableStaggeredCredit":false,"isOnoCmtEmailCampaign":false,"onoSendEmailToArcamax":false,"prePingXverifyDataLog":false,"pushnamiSubdomainPath":null,"yieldLookbackInterval":60,"emailDupFlowCookieMerge":false,"stopSpamUserPostAttempt":0,"enableExternalLeadConfig":false,"profanityBlockingEnabled":true,"site_subsource_parameter":null,"UserLandingCategorisation":false,"enableLinkoutOfferCapping":true,"enableUserIdBucketLogging":false,"useTargetEpcForConversion":true,"checkPartialTcpaForDupUser":false,"creditRecencyThresholdTime":24,"doNotFireAnyConversionPixel":false,"duplicateUserByProfileScore":false,"refillCookieOfReturningUser":false,"enableUserIdBasedConversionV1":true,"permanentSubdomainRedirection":true,"XverifyInvalidPhoneRedirect403":false,"enablePrepingYieldOptimization":false,"partnerBasedConversionTracking":false,"checkRecentCreditsForConversion":true,"doNotFireConversionForDuplicate":0,"smartFlowUserCategorizationFlag":false,"enablePrepingYieldOptimizationFilter":false,"fireDripsConversionWithoutEmailSubmit":0,"disableSpamanalyst":true,"enableNetacuity":true,"enableAgedLeadsV2":true,"disableAgedLeadsOld":true,"enableAnuraServerSide":true,"dnc_failure_threshold_unblock":true,"anura_failure_threshold_unblock":true,"xverify_failure_threshold_unblock":true,"xverifymobile_failure_threshold_unblock":true,"campaign_id":"zqkxq-1682","experiment_type":"FLOW","enableEnroll":false};
var experiment_config = {"direct":null,"pushObj":false,"skipreg":null,"criteria":null,"settings":{"linkout":{"open":3}},"surveyId":null,"surveyv2":true,"offerCapOW":false,"epcPriority":true,"smartSurvey":true,"surveyOnPII":true,"tValueParam":null,"RPUTargeting":false,"enableBudget":false,"enableCaching":false,"epcPriorityV2":false,"exclusivityOW":true,"linkout_group":143,"linkout_order":"forced-pos-cap","surveyVersion":5,"tcpaonLanding":false,"RPUTargetingV2":false,"surveyOnLander":false,"tValueFallback":null,"conversionEvent":"EmailSubmit","limit_linkout_2":null,"linkoutStrategy":{"strategy":"v3","dimensionGroupId":62},"linkout_group_2":null,"linkout_order_2":"forced-pos-cap","options_pruning":false,"exclusiveGroupId":"AdvertiserTag","offerwallVersion":2,"v5_survey_config":{"exp_slots":2,"hpcvr_weight":null,"revenue_weight":null,"totalbids_weight":null,"enableAdditionalTCPATags":true,"enableGreedyAdditionalTags":true,"offer_rule_rpm_impression_threshold":500,"offer_rule_rpm_posted_leads_threshold":50,"offer_rule_rpm_rule_matched_threshold":60,"moveTCPAConsentAboveOptionsAllQuestions":true,"excludeQuestionsToNotMoveTCPAConsentAboveOptions":[29,559,587,634,719,720,721,726]},"autoSurveyVersion":"v6","enableLuckyOrange":false,"enableStatsSurvey":true,"logOnoUnsubStatus":false,"surveyQuestionCap":0,"blacklisted_offers":[],"emailLeadExclusive":true,"enableDataByPrepop":true,"enableOneonOneTCPA":true,"enableSentryClient":false,"frequencyCappingOW":false,"piiDataNotRequired":false,"statsSurveyVersion":"v1","bypassLiveOnoUnsubs":true,"enableExtraTCPATags":true,"enableStatsSurveyV4":true,"enableSurveyPruning":false,"pushnami_prompt_loc":null,"showSurveyQuesImage":true,"subDomainDateFormat":null,"directToLoSkipSurvey":true,"enableDelayedPosting":true,"enableDynamicLinkout":true,"enableExpressUserReg":false,"enableStickyNoThanks":false,"lastRegistrationPage":"register-step2","trackTrustedFormLoad":true,"warmupQuestionsLimit":1,"enableHereAutoSuggest":false,"enableHostPostPruning":false,"enablePushNamiOverlay":false,"enableRpmBasedRanking":false,"surveySkipQuestionCap":false,"disableHereAutoSuggest":false,"enableDynamicLinkout_2":false,"enableExitMonetization":true,"enableIntermediateTcpa":true,"enableIpAddressDetails":false,"cidLevelProgressionData":true,"enableHistoryTagsInFeed":true,"enableTCPAOptOutConsent":true,"returnPiiDataExpressReg":true,"trackFluentAppwallClick":true,"enableCustomBotDetection":true,"enableExitMonetization_2":false,"exitMonetisationPageName":"thankyou","filterDuplicateQuestions":false,"offerwallRankingStrategy":null,"adjustForFinalSortingFlag":true,"enableAutoRedirectRegUser":true,"enableExclusiveToAllGroup":true,"enable_blacklisted_offers":true,"show_dynamic_tag_together":false,"enableCookieDuplicateCheck":false,"enableEmailCorrectionOnReg":false,"enableGenericLinkoutAbTest":false,"enablePushNamiOptimization":false,"profileScoreExcludeColumns":[],"surveyDefaultQuestionCount":5,"surveyFallbackOptimisation":true,"enableAutoPopulateDBRegUser":false,"enableEagerIntermediateTcpa":false,"forceDynamicBrandingKeyword":"pubgiveawaypehdup,{t8|(tndgeneric)}","enableSurveyLinkoutHandshake":true,"skipLinkoutIfAllOffersViewed":true,"enableDelayedExclusivityCheck":true,"showExploratoryAtFirstPosition":true,"includeOnlyHouseNumberInHEREApi":false,"openOfferInSameTabForIOSWebview":true,"skipZeroRPMLinkoutOffersForBids":true,"changePreferNotAnswerToNoneApply":false,"expressProgressBarForInitialQues":false,"usePhoneEmailHashForHistoricData":false,"changeContinueToSkipOnNoSelection":false,"UsePreviousVisitDataForLeadPosting":true,"enableAutoRedirectRegUserToLinkout":false,"enableDelayedExclusivityCheckForLiveLead":true,"enableAnuraSpam":false,"enableAntispamPixel":true,"enableAnuraSpamCheck":true,"bla_failure_threshold_unblock":true,"enableRegexValidationForEmail":true,"enableAsync":true,"enableAsyncTimeEventLogging":true,"extraMarketingNameBasedOfferPosting":true,"useMaxNewPrepingFlag":true};
var device_atlas_config = {"isBrowser":"1","isRobot":"1","primaryHardwareType":"Desktop","osFamily":"Windows","osName":"Windows 98","osVendor":"Microsoft","botName":"HTTrack","displayWidth":null,"displayHeight":null,"diagonalScreenSize":null};
