"use strict";function ownKeys(object,enumerableOnly){var keys=Object.keys(object);if(Object.getOwnPropertySymbols){var symbols=Object.getOwnPropertySymbols(object);enumerableOnly&&(symbols=symbols.filter(function(sym){return Object.getOwnPropertyDescriptor(object,sym).enumerable;})),keys.push.apply(keys,symbols);}return keys;}
function _objectSpread(target){for(var i=1;i<arguments.length;i++){var source=null!=arguments[i]?arguments[i]:{};i%2?ownKeys(Object(source),!0).forEach(function(key){_defineProperty(target,key,source[key]);}):Object.getOwnPropertyDescriptors?Object.defineProperties(target,Object.getOwnPropertyDescriptors(source)):ownKeys(Object(source)).forEach(function(key){Object.defineProperty(target,key,Object.getOwnPropertyDescriptor(source,key));});}return target;}
function _defineProperty(obj,key,value){if(key in obj){Object.defineProperty(obj,key,{value:value,enumerable:true,configurable:true,writable:true});}else{obj[key]=value;}return obj;}
function asyncGeneratorStep(gen,resolve,reject,_next,_throw,key,arg){try{var info=gen[key](arg);var value=info.value;}catch(error){reject(error);return;}if(info.done){resolve(value);}else{Promise.resolve(value).then(_next,_throw);}}
function _asyncToGenerator(fn){return function(){var self=this,args=arguments;return new Promise(function(resolve,reject){var gen=fn.apply(self,args);function _next(value){asyncGeneratorStep(gen,resolve,reject,_next,_throw,"next",value);}function _throw(err){asyncGeneratorStep(gen,resolve,reject,_next,_throw,"throw",err);}_next(undefined);});};}
class Lander{constructor(app){var _window$experiment_co,_window$experiment_co2,_campaign_config,_window$experiment_co3,_window$experiment_co4,_window$experiment_co5,_window$experiment_co6,_window$customData,_window$customData$us,_window,_window$experiment_co7,_customData,_window2,_window2$experiment_c,_window3,_window3$campaign_con,_config,_config2,_window$customData2,_window$customData3;this.app=app||window.appInstance||new App();if(window.customData.isSubdomain){this.app.parentListner(()=>{this.isFetchParamsCalled=false;this.fetchParams();});}
this.app.loadDynamicDisclaimer();this.moveDirect=false;this.isCampaignInitiated=false;this.trackViewportExit();this.isViewportInterstitialShown=false;this.closeOnBodyclick();this.addExitInterstitialEvtListeners();this.mobileViewportexit();this.isKeyupCalled=false;this.app.element('landerPage').visible(false);this.eventTracker=new LEADGEN.tracker();this.valueChangedInEmailInput=false;this.isExpressReg=((_window$experiment_co=window.experiment_config)===null||_window$experiment_co===void 0?void 0:_window$experiment_co.enableExpressUserReg)||false;this.delayExpressUserFlow=((_window$experiment_co2=window.experiment_config)===null||_window$experiment_co2===void 0?void 0:_window$experiment_co2.delayExpressUserFlow)||3000;this.expressUserFlowTimeout=null;this.loaderEle=document.querySelector("#loaderSpinner");this.loaderDelay=3000;this.loaderStepCount=3;this.loaderStepLimit=parseInt(this.loaderDelay/this.loaderStepCount);this.loaderCheckTimeout=null;this.campaignId=((_campaign_config=campaign_config)===null||_campaign_config===void 0?void 0:_campaign_config.campaign_id)||'';this.loaderStepComplete=[];this.loadStart=0;this.isFetchParamsCalled=false;window.pushStatus='';window.pushnamiComplete=false;window.underTheTabOfferPrepopUrl=[];window.underTheTabOfferId=null;this.pushOverlayCollapsed=false;this.enablePushNamiOverlay=((_window$experiment_co3=window.experiment_config)===null||_window$experiment_co3===void 0?void 0:_window$experiment_co3.enablePushNamiOverlay)||false;this.childHidden=[];this.autoRedirectTimeout=(((_window$experiment_co4=window.experiment_config)===null||_window$experiment_co4===void 0?void 0:_window$experiment_co4.expressRegAutoRedirectTimeout)||20)*1000;this.twoStepCtaClickTimeout=null;this.enableExpressRegAutoAction=((_window$experiment_co5=window.experiment_config)===null||_window$experiment_co5===void 0?void 0:_window$experiment_co5.enableExpressRegAutoAction)||false;this.isUnifiedFlowRedirect=((_window$experiment_co6=window.experiment_config)===null||_window$experiment_co6===void 0?void 0:_window$experiment_co6.enableUnifiedFlow)&&((_window$customData=window.customData)===null||_window$customData===void 0?void 0:(_window$customData$us=_window$customData.user_profile)===null||_window$customData$us===void 0?void 0:_window$customData$us.moveDirectEmail);if((_window=window)!==null&&_window!==void 0&&(_window$experiment_co7=_window.experiment_config)!==null&&_window$experiment_co7!==void 0&&_window$experiment_co7.enableLanderBackButtonOveride){setTimeout(()=>{var queryString=window.location.search;var link=window.location.href;var url=new URL(link);history.pushState({redirect:1},'redirect',url.origin+'/lander-redirect'+queryString);setTimeout(()=>{history.pushState({lander:1},'lander',link);},500);},500);}
if(this.isUnifiedFlowRedirect){try{var loader=this.loaderEle||document.querySelector('div[data-loader-delay]');var display_css=document.createElement('style');display_css.innerText=".show_loader { display: ".concat(window.getComputedStyle(loader).display||'block'," !important; }");document.head.appendChild(display_css);if(loader){loader.classList.add('show_loader');}}catch(e){console.log('unified flow loader detection failure');}}
window.noDataPreprop=true;this.missingFields=[];window.emailSubmited=false;window.expressCurrStepComplete=null;window.isExpressFlowError=false;localStorage.removeItem('pushnamiLoaded');if((_customData=customData)!==null&&_customData!==void 0&&_customData.isUkTraffic){if(!localStorage.getItem('gdpr_granted')){this.app.element('cookiepopup').show('flex');}}
if(this.isExpressReg){this.emailGl=this.app.getUrlSearchParams(window.location.href).getPii('emailAddress');this.emailGl=this.emailGl?this.app.removeMacrosFromString(this.emailGl):localStorage?localStorage.getItem('survey-prefix-emailAddress'):null;if(!this.emailGl&&document.body.getAttribute('data-newUserFlow')){this.eventTracker.trackCustomEvent('imp','block','expressflowcontinueshown',{event:'ExpressFlowContinueShown',cid:this.campaignId,domain:config.hostApi,usertype:"NewUserEmailInput"});window.emailValidateCB=()=>{window.emailValidateCB=null;window.emailSubmited=true;this.eventTracker.trackCustomEventPromise('button','click','email-submit',{event:'EmailSubmit',cid:this.campaignId,domain:config.hostApi,usertype:"NewUserEmailInput"}).then(()=>{if(window.dataLayer)window.dataLayer.push({event:'emailsubmit'});this.app.checkAndFirePartnerPixel(true).then(()=>{console.log('postback pixel fire complete');}).catch(err=>{console.log('postback pixel error: ',err);});});this.execValidateUser();};}}
if(document.getElementById('submituserdetials')){var _self=this;document.getElementById('submituserdetials').addEventListener('click',function(e){window.noDataPreprop=false;document.getElementById("entersweep").click();if(document.querySelector('.newuser'))document.querySelector('.newuser').parentElement.removeChild(document.querySelector('.newuser'));if(!_self.app.checkFullParamData()&&!window.isExpressFlowError){_self.hideLoaderAndDisplayPII('NewUserPartialPrepopData');}else{window.newUserWithFullPrepopData=true;}});}
if((_window2=window)!==null&&_window2!==void 0&&(_window2$experiment_c=_window2.experiment_config)!==null&&_window2$experiment_c!==void 0&&_window2$experiment_c.enableAntispamPixel||(_window3=window)!==null&&_window3!==void 0&&(_window3$campaign_con=_window3.campaign_config)!==null&&_window3$campaign_con!==void 0&&_window3$campaign_con.enableAntispamPixel){this.app.loadAntiSpam();}
if((_config=config)!==null&&_config!==void 0&&_config.anuraInstanceId&&(_config2=config)!==null&&_config2!==void 0&&_config2.enableAnuraSpamCheck&&!((_window$customData2=window.customData)!==null&&_window$customData2!==void 0&&_window$customData2.isSpam)){var script=document.createElement('script');var _self2=this;script.onload=function(){console.log('Anura Loaded');anuraLoad(function(res){window.anuraLoadedTest=true;if(_self2.isExpressReg){window.expressCurrStepComplete='AnuraJSComplete';_self2.eventTracker.trackCustomEvent('com','block','anurajscomplete',{event:'AnuraJSComplete',cid:_self2.campaignId,domain:config.hostApi,anuraData:res});if(!_self2.emailGl&&document.body.getAttribute('data-newUserFlow')){_self2.loaderEle.setAttribute('data-usertype','partialdatawoemail');}else{_self2.execValidateUser(true);}}});};script.src="/js/anura.js";document.head.appendChild(script);}else{if(this.isExpressReg){if(!this.emailGl&&document.body.getAttribute('data-newUserFlow')){this.loaderEle.setAttribute('data-usertype','partialdatawoemail');}else{setTimeout(()=>{this.execValidateUser(true);},3000);}}}
this.fetchParams();if((_window$customData3=window.customData)!==null&&_window$customData3!==void 0&&_window$customData3.enableNotifyAi&&flowData&&flowData.flow_page_slug==='lander'){var script=document.createElement("script");script.type="text/javascript";script.src="https://trk-keingent.com/scripts/push/script/64d5pzvgj0?url="+encodeURI(self.location.hostname);script.onload=function(){push_init();var sessionId=window.session_id;setSessionId(sessionId);push_subscribe();};document.getElementsByTagName("head")[0].appendChild(script);}}
handleGoogleOptimiser(data,app){var eventTracker=window.LEADGEN?new LEADGEN.tracker():null;if(eventTracker){eventTracker.trackCustomEvent('optimise','imp','google',{event:'GoogleOptimiseDataEvent',data:JSON.stringify(data)});}
app.setGoogleOptimiseData(data).then(res=>{}).catch(err=>{if(eventTracker){eventTracker.trackCustomEvent('optimise','err','google',{event:'GoogleOptimiseDataErrorEvent',error:JSON.stringify(err)});}});}
onInit(){var _window4,_window4$campaign_dat,_window6,_window6$campaign_dat;var redirect=arguments.length>0&&arguments[0]!==undefined?arguments[0]:true;this.app.getTracking();var cid='';localStorage.setItem('landingUrl',window.location.href);if(window.location.search.search('cid')>-1){cid=this.app.getParam(document.URL,'cid');}else if(window.location.search.search('campaignId')>-1){cid=this.app.getParam(document.URL,'campaignId');}else if(window.location.pathname.search('/m')>-1){cid=window.location.pathname.replace('/m','').split('/')[0];}else if((_window4=window)!==null&&_window4!==void 0&&(_window4$campaign_dat=_window4.campaign_data)!==null&&_window4$campaign_dat!==void 0&&_window4$campaign_dat.campaignId){var _window5,_window5$campaign_dat;cid=(_window5=window)===null||_window5===void 0?void 0:(_window5$campaign_dat=_window5.campaign_data)===null||_window5$campaign_dat===void 0?void 0:_window5$campaign_dat.campaignId;}
if(window.location.search.search('cid')===-1&&!((_window6=window)!==null&&_window6!==void 0&&(_window6$campaign_dat=_window6.campaign_data)!==null&&_window6$campaign_dat!==void 0&&_window6$campaign_dat.campaignId)&&window.location.search.search('campaignId')===-1&&window.location.pathname.search('/m')===-1){this.app.postMaxEvents('LanderWithCampaign');this.app.postEvents('landerFallback',{});window.location.href='/lander.html';}else{this.app.postMaxEvents('LanderWithCampaign');this.app.postEvents('landerLoad',{cid:cid});}
this.app.loadPushProvider('lander');try{var _window$campaign_conf;if(window.campaign_config&&!((_window$campaign_conf=window.campaign_config)!==null&&_window$campaign_conf!==void 0&&_window$campaign_conf.disableSpamanalyst)){var saScript=document.createElement('script');saScript.src='https://pxlgnvwe-a.akamaihd.net/javascripts/browserfp.min.js?templateId=24';saScript.async='async';saScript.onload=function(){try{var fp_instance=new browserfp();var pageAttr={};pageAttr.template_id=24;pageAttr.cmp_id=cid;pageAttr.vi_id=session_id;fp_instance.setPageAttr(pageAttr);fp_instance.sendViewData();}catch(e){if(window.Sentry&&typeof window.Sentry.captureException==='function'){window.Sentry.captureException(e);}}};document.body.appendChild(saScript);}}catch(e){}
if(cid=='yjr45'){(function(w,d,t,r,u){var f,n,i;w[u]=w[u]||[],f=function f(){var o={ti:'56059898'};o.q=w[u],w[u]=new UET(o),w[u].push('pageLoad');},n=d.createElement(t),n.src=r,n.async=1,n.onload=n.onreadystatechange=function(){var s=this.readyState;s&&s!=='loaded'&&s!=='complete'||(f(),n.onload=n.onreadystatechange=null);},i=d.getElementsByTagName(t)[0],i.parentNode.insertBefore(n,i);})(window,document,'script','//bat.bing.com/bat.js','uetq');}
if(this.loaderEle){if(this.isExpressReg){window.expressCurrStepComplete='ExpressFlowLoaderShown';this.eventTracker.trackCustomEvent('imp','section','expressflowloader',{event:'ExpressFlowLoaderShown',cid:this.campaignId,domain:config.hostApi});this.loadStart=Date.now();this.loaderEle.setAttribute('data-step',1);this.loaderStepComplete.push(1);}
this.app.element('loaderSpinner').show('flex');}
this.app.element('landerPage').visible(false);this.registerInputs();if(redirect){this.loadFromLocalStorage();}
localStorage.removeItem('max-pixel-called');var queryString=window.location.search;this.app.postApi(config.hostApi+'/api/survey/campaign-initiate'+queryString+'&uid='+session_id+'&leadgenuid='+cookie_id,{cid:cid,system:{sw:screen.width,sh:screen.height,datetime:this.app.getDateTime()},referrerUrl:document.referrer,navigator:{vendorSub:window.navigator.vendorSub,productSub:window.navigator.productSub,vendor:window.navigator.vendor,maxTouchPoints:window.navigator.maxTouchPoints,hardwareConcurrency:window.navigator.hardwareConcurrency,cookieEnabled:window.navigator.cookieEnabled,appCodeName:window.navigator.appCodeName,appName:window.navigator.appName,appVersion:window.navigator.appVersion,platform:window.navigator.platform,product:window.navigator.product,userAgent:window.navigator.userAgent,language:window.navigator.language,languages:window.navigator.languages,onLine:window.navigator.onLine,doNotTrack:window.navigator.doNotTrack}}).then(x=>{var _window$campaign_conf2,_window$experiment_co8,_window$campaign_conf3,_flowData;if(!this.isExpressReg){if(!this.isUnifiedFlowRedirect){if(this.loaderEle){this.app.element('loaderSpinner').hide();}
this.app.element('landerPage').visible(true);document.body.setAttribute('data-lander','visible');}}else{window.expressCurrStepComplete='CampaignInitiateComplete';if(this.loaderEle){var elapsedDiff=Date.now()-this.loadStart;if(elapsedDiff>this.loaderStepLimit){this.loaderEle.setAttribute('data-step',2);this.loaderStepComplete.push(2);}else{setTimeout(()=>{this.loaderEle.setAttribute('data-step',2);this.loaderStepComplete.push(2);},this.loaderStepLimit-elapsedDiff);}}}
console.log('Survey Initiated');this.isCampaignInitiated=true;var form=this.app.element('landerform').all();if(x.response){form.action=x.response.formAction;window.globalAccessToken=x.response.accessToken;localStorage.setItem('base64code',x.response.accessToken);}
if(this.moveDirect||this.isUnifiedFlowRedirect){var _window$customData4;if((_window$customData4=window.customData)!==null&&_window$customData4!==void 0&&_window$customData4.enablePushNami&&window.pushStatus&&this.enablePushNamiOverlay&&!window.pushnamiComplete&&!this.app.isIOS()){document.body.addEventListener('overlayShownComplete',()=>{this.checkAndExecuteAnura(true);});}else{this.checkAndExecuteAnura();}}
if((!window.config.anuraInstanceId||!window.config.enableAnuraSpamCheck)&&this.isExpressReg){if(!this.emailGl&&document.body.getAttribute('data-newUserFlow')){this.loaderEle.setAttribute('data-usertype','partialdatawoemail');}else{this.execValidateUser();}}
var enableUnderTheTabFeature=((_window$campaign_conf2=window.campaign_config)===null||_window$campaign_conf2===void 0?void 0:_window$campaign_conf2.enableUnderTheTabFeature)||((_window$experiment_co8=window.experiment_config)===null||_window$experiment_co8===void 0?void 0:_window$experiment_co8.enableUnderTheTabFeature);if(enableUnderTheTabFeature&&flowData&&flowData.flow_page_slug==='lander'&&((_window$campaign_conf3=window.campaign_config)===null||_window$campaign_conf3===void 0?void 0:_window$campaign_conf3.experiment_type)==='FLOW'){this.app.getunderTheTabOffers();}
var self=this;if(document.getElementById('entersweeps')){document.getElementById('entersweeps').addEventListener('keyup',function(e){if(this.value||e.target.value||localStorage&&localStorage.getItem('survey-prefix-emailAddress'))self.valueChangedInEmailInput=true;});}
this.app.checkAndFirePartnerPixel().then(()=>{console.log('postback pixel fire complete');});setTimeout(()=>{if(document.querySelector('.enable-focus')){document.querySelector('.enable-focus').focus();}else{if(document.getElementById('entersweeps')){document.getElementById('entersweeps').focus();}}},500);if(window.marketingList&&["lander"].includes((_flowData=flowData)===null||_flowData===void 0?void 0:_flowData.flow_page_slug)){window.marketingList.getMarketingData('populatelist',true);}}).catch(err=>{if(window.Sentry&&typeof window.Sentry.captureException==='function'){window.Sentry.captureException(err);}
console.log('campaign initiate err: ',err);});this.inputHaltInterstitial();var self=this;if(document.getElementById('updatepiidetails')){document.getElementById('updatepiidetails').addEventListener('click',function(){if(self.twoStepCtaClickTimeout)clearTimeout(self.twoStepCtaClickTimeout);window.expressCurrStepComplete='NotYouClicked';var notYouClickStep=!window.noDataPreprop?"NewUserPrepopNotYouClicked":"FullUserNotYouClicked";self.eventTracker.trackCustomEvent('click','section','expressflownotyouclick',{event:'ExpressFlowNotYouClick',cid:self.campaignId,domain:config.hostApi,usertype:notYouClickStep});self.hideLoaderAndDisplayPII(notYouClickStep);if(document.querySelector('.newuser'))document.querySelector('.newuser').parentElement.removeChild(document.querySelector('.newuser'));if(self.expressUserFlowTimeout)clearTimeout(self.expressUserFlowTimeout);});}
if(window.experiment_config&&window.experiment_config.enableCustomBotDetection&&document.querySelector('#landerform')){var hiddenElement='<div class="confirmemail" style="display: none;"> <input type="text" name="confirm_email" id="confirm_email"> </div>';document.querySelector('#landerform').insertAdjacentHTML('beforeend',hiddenElement);}
if(window.dataLayer){window.dataLayer.push({event:'LandingImpression'});};}
checkAndExecuteAnura(isPushnamiOverlayShown){if(config.enableAnuraSpamCheck&&config.anuraInstanceId&&localStorage&&!localStorage.getItem('isAnuraSpam')){this.app.checkAnuraExecution().then(res=>{if(isPushnamiOverlayShown){this.eventTracker.trackCustomEvent('imp','section','pushoverlayprompt',{event:'pushOverlayPromptAutoRedirected',pushstatus:window.pushStatus});}
this.fireEmailSubmitAndRedirect();});}else{if(isPushnamiOverlayShown){this.eventTracker.trackCustomEvent('imp','section','pushoverlayprompt',{event:'pushOverlayPromptAutoRedirected',pushstatus:window.pushStatus});}
this.fireEmailSubmitAndRedirect();}}
fireEmailSubmitAndRedirect(){this.eventTracker.trackCustomEventPromise('button','click','email-submit',{event:'EmailSubmit',moveDirect:true}).then(()=>{if(window.dataLayer)window.dataLayer.push({event:'emailsubmit'});var submitButton=document.getElementsByTagName('form');if(window.isSpa){var submitbtn=document.getElementById('entersweep');if(submitbtn)submitbtn.click();return;}
submitButton[0].submit();});}
checkAndRemoveTransactionId(){var key='transaction_id';try{var searchParams=this.app.getUrlSearchParams(window.location.href);var piimap=this.app.getPIIMapping();if(!searchParams.get(piimap[key])){localStorage.removeItem('survey-prefix-'+piimap[key]);if(window.setIframe&&window.customData.isSubdomain){this.app.checkLocalStorageData().removeData('survey-prefix-'+piimap[key]);}}}catch(err){console.log(err);}}
fetchParams(){if(!this.isFetchParamsCalled){this.isFetchParamsCalled=true;this.app.fetchParamsFromURLAndSetToLocalStorage();this.checkAndRemoveTransactionId();this.loadFromLocalStorage();}}
mapToSystemValue(name){var piimap=this.app.getPIIMapping();return piimap[name.toLowerCase()]||name;}
registerInputs(){document.querySelectorAll('input, select').forEach(i=>{i.addEventListener('change',e=>{this.saveToLocalStorage(e);});});}
saveToLocalStorage(event){var elem=event.target;localStorage.setItem('survey-prefix-'+elem.name,elem.value);if(window.setIframe&&window.customData.isSubdomain){this.app.checkLocalStorageData().setData('survey-prefix-'+elem.name,elem.value);}}
loadFromLocalStorage(){document.querySelectorAll('input, select').forEach(ele=>{var _customData2,_customData3;var data=localStorage?localStorage.getItem('survey-prefix-'+ele.name):null;if((_customData2=customData)!==null&&_customData2!==void 0&&_customData2.user_profile&&(_customData3=customData)!==null&&_customData3!==void 0&&_customData3.user_profile[ele.name]){var _customData4;data=(_customData4=customData)===null||_customData4===void 0?void 0:_customData4.user_profile[ele.name];}
if(data){if(ele.name=='gender'){if(["male","female"].includes(ele.value.toLowerCase())){ele.value=data;}}else if(ele.name=='gendervalue1'){if(ele.value==data){ele.click();}}else{ele.value=data;}}else{var _window$experiment_co9,_window$customData5,_window$customData6,_window$customData7;if(ele.name=='zipcode'&&(_window$experiment_co9=window.experiment_config)!==null&&_window$experiment_co9!==void 0&&_window$experiment_co9.enableIpAddressDetails&&(_window$customData5=window.customData)!==null&&_window$customData5!==void 0&&_window$customData5.ipAddressDetails&&(_window$customData6=window.customData)!==null&&_window$customData6!==void 0&&_window$customData6.ipAddressDetails['zip-code']&&((_window$customData7=window.customData)===null||_window$customData7===void 0?void 0:_window$customData7.ipAddressDetails['zip-code'])>0){ele.value=window.customData.ipAddressDetails['zip-code'];}}});}
displayInterstitial(){if(document.getElementById('directLinkout')&&!this.isViewportInterstitialShown){this.isViewportInterstitialShown=true;document.getElementById('directLinkout').style.display='flex';var urlParams=this.app.getUrlSearchParams(window.location.href);var cid=urlParams.get('cid');var domainName=this.app.getDomainName();var offerID={freesamplesprousa:540,theamericansweepstakes:545};document.getElementById('getOffer').href='https://imtrk.go2cloud.org/aff_c?offer_id='+offerID[domainName]+'&aff_id=1&aff_sub='+cid+'&aff_sub3='+session_id;document.getElementById('bodyOver').style.overflow='hidden';this.eventTracker.trackCustomEvent('imp','section','interstitial',{event:'ExitInterstitialShown'});}}
trackViewportExit(){var self=this;document.addEventListener('mouseout',event=>{if(event.clientY<=0||event.clientX<=0||event.clientX>=window.innerWidth||event.clientY>=window.innerHeight){self.displayInterstitial();}});}
inputHaltInterstitial(){var self=this;var showOverlay=function showOverlay(){setTimeout(()=>{self.displayInterstitial("input keyup");},30000);};var inputElem=document.getElementById('entersweeps');if(inputElem){if(inputElem.value==''&&!this.valueChangedInEmailInput){inputElem.addEventListener("keyup",function(){if(!self.isKeyupCalled&&this.value.trim().length>0){self.isKeyupCalled=true;showOverlay();}});}else{showOverlay();}}}
addExitInterstitialEvt(){if(document.getElementById('closeInterstitial')){document.getElementById('closeInterstitial').addEventListener('click',()=>{document.getElementById('directLinkout').style.display='none';document.getElementById('bodyOver').style.overflow='auto';this.eventTracker.trackCustomEvent('com','section','interstitial',{event:'ExitClosedClicked'});});}
if(document.getElementById('getOffer')){document.getElementById('getOffer').addEventListener('click',()=>{document.getElementById('directLinkout').style.display='none';document.getElementById('bodyOver').style.overflow='auto';this.eventTracker.trackCustomEvent('click','section','interstitial',{event:'ExitCtaClicked'});});}}
addExitInterstitialEvtListeners(){if(window.isV2Version)this.addExitInterstitialEvt();window.addEventListener('DOMContentLoaded',()=>this.addExitInterstitialEvt());}
mobileViewportexitContentLoaded(){var self=this;if(document.getElementById('entersweeps')){setTimeout(()=>{if((document.getElementById('entersweeps')&&document.getElementById('entersweeps').value==''||localStorage&&localStorage.getItem('survey-prefix-emailAddress'))&&!this.valueChangedInEmailInput){self.displayInterstitial();}},20000);}}
mobileViewportexit(){if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){if(window.isV2Version)this.mobileViewportexitContentLoaded();window.addEventListener('DOMContentLoaded',()=>this.mobileViewportexitContentLoaded());}}
closeOnBodyclick(){var self=this;if(document.getElementById('directLinkout')){window.addEventListener('click',event=>{if(event.target==document.querySelector('#directLinkout')){document.getElementById('directLinkout').style.display='none';document.getElementById('bodyOver').style.overflow='auto';self.eventTracker.trackCustomEvent('com','section','interstitial',{event:'ExitClosedClicked'});}});}}
validateExpressUser(){var _this=this;return _asyncToGenerator(function*(){try{var _window$config,_resp$extra_info;var inputs=document.querySelector("#landerform").getElementsByTagName('input');var txtarea=document.querySelector("#landerform").getElementsByTagName('textarea');var allEle=[...inputs,...txtarea];if(window.campaign_config&&window.campaign_config.profanityBlockingEnabled){_this.app.redirectUserToLanderOnProfanity(null,allEle);}else{allEle.forEach(inpEl=>{_this.app.handleProfanityCheck(null,inpEl);});}
_this.fetchParams();var url=((_window$config=window.config)===null||_window$config===void 0?void 0:_window$config.hostApi)+"/api/app/validate-user";var email=localStorage?localStorage.getItem('survey-prefix-emailAddress'):null;var fname=localStorage?localStorage.getItem('survey-prefix-userFname'):null;var lname=localStorage?localStorage.getItem('survey-prefix-userLname'):null;var gender=localStorage?localStorage.getItem('survey-prefix-gendervalue1'):null;var address=localStorage?localStorage.getItem('survey-prefix-userAddress'):null;var city=localStorage?localStorage.getItem('survey-prefix-cityName'):null;var state=localStorage?localStorage.getItem('survey-prefix-stateCode'):null;var mobile=localStorage?localStorage.getItem('survey-prefix-mobile'):null;var zip=localStorage?localStorage.getItem('survey-prefix-zipcode'):null;var date=localStorage?localStorage.getItem('survey-prefix-dobdate'):null;var month=localStorage?localStorage.getItem('survey-prefix-dobmonth'):null;var year=localStorage?localStorage.getItem('survey-prefix-dobyear'):null;var genderTypes=['m','f','male','female'];gender=gender?gender.toLowerCase():null;if(gender&&genderTypes.includes(gender)){if(gender==='m'||gender==='male'){gender="male";}else{gender="female";}}else{gender='';}
var params={sessionId:window.session_id};if(email){var _gender;params.emailAddress=email===null||email===void 0?void 0:email.trim();params.cityName=city===null||city===void 0?void 0:city.trim();params.gender=(_gender=gender)===null||_gender===void 0?void 0:_gender.trim();params.mobile=mobile===null||mobile===void 0?void 0:mobile.trim();params.stateCode=state===null||state===void 0?void 0:state.trim();params.userAddress=address===null||address===void 0?void 0:address.trim();params.userDOB=date&&month&&year?year.trim()+'-'+month.trim()+'-'+date.trim():null;params.userFname=fname===null||fname===void 0?void 0:fname.trim();params.userLname=lname===null||lname===void 0?void 0:lname.trim();params.zipcode=zip===null||zip===void 0?void 0:zip.trim();var mailformat=/^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;if(!mailformat.test(email)){params.emailAddress=null;}
Object.keys(params).forEach(key=>{if((params[key]===null||params[key]=='')&&key!='emailAddress'){delete params[key];}});}else{_this.missingFields.push('emailAddress');}
var resp=yield _this.app.postApi(url,params);window.expressCurrStepComplete='ValidateUserComplete';window.validateUserResponse=resp;_this.eventTracker.trackCustomEvent('com','block','validatusercomplete',{event:'ValidateUserComplete',cid:_this.campaignId,domain:config.hostApi,data:resp});console.log('validation data res: ',resp);if(_this.loaderEle){var elapsedDiff=Date.now()-_this.loadStart;if(elapsedDiff>_this.loaderStepLimit*2){_this.loaderEle.setAttribute('data-step',3);_this.loaderStepComplete.push(3);}else{setTimeout(()=>{_this.loaderEle.setAttribute('data-step',3);_this.loaderStepComplete.push(3);},_this.loaderStepLimit*2-elapsedDiff);}}
if(document.querySelectorAll('.user-email').length>0){var emailid=(resp===null||resp===void 0?void 0:resp.email_id)||email;if(emailid)document.querySelectorAll('.user-email').forEach(el=>el.innerText=emailid);}
if((resp===null||resp===void 0?void 0:(_resp$extra_info=resp.extra_info)===null||_resp$extra_info===void 0?void 0:_resp$extra_info.length)>0){resp.extra_info.forEach(el=>{localStorage.setItem('survey-prefix-'+el.key,el.value);if(window.setIframe&&window.customData.isSubdomain){_this.app.checkLocalStorageData().setData('survey-prefix-'+el.key,el.value);}});}
if(document.querySelectorAll('.user-fname').length>0){var nm=fname;if(nm)document.querySelectorAll('.user-fname').forEach(el=>el.innerText=nm);if(document.querySelector('#reUser')&&nm)document.querySelector('#reUser').style.display='inline-block';}
if(resp!==null&&resp!==void 0&&resp.is_opt_out){var md5Script=document.createElement('script');md5Script.src="/js/md5-converter.js";md5Script.defer=true;document.body.appendChild(md5Script);var _self3=_this;md5Script.onload=function(){window.location=location.origin+'/403.html?v='+_self3.app.getEncodedEmailPhoneHash();};}
return resp;}catch(e){if(window.Sentry&&typeof window.Sentry.captureException==='function'){window.Sentry.captureException(e);}
console.log("Express User Validation Failure: ",e);}})();}
addResetNerrorClass(el){if(el&&!el.value){el.classList.add('error');}}
hideElandAddClass(el){if(el){if(el.parentElement&&el.parentElement.getAttribute('data-parentdiv')){el.parentElement.classList.add('hideparent');}
if(el.parentElement&&el.parentElement.parentElement&&el.parentElement.parentElement.getAttribute('data-parentdiv')&&el.parentElement.parentElement.children){var menu=el.parentElement.parentElement;var children=menu.children||[];this.childHidden=[];Object.entries(children).forEach(_ref=>{var[key,value]=_ref;if(value&&value.classList.contains('hideparent'))this.childHidden.push(value);});if(this.childHidden.length==children.length&&el.parentElement&&el.parentElement.parentElement){el.parentElement.parentElement.classList.add('hideparent');el.parentElement.style.display='none';}}
el.style.display='none';el.classList.add('hideinput');}}
hideLoaderAndDisplayPII(){var userType=arguments.length>0&&arguments[0]!==undefined?arguments[0]:'';var missingFields=arguments.length>1&&arguments[1]!==undefined?arguments[1]:[];if(this.loaderEle){if(this.loaderStepComplete.length==4){clearTimeout(this.loaderCheckTimeout);this.eventTracker.trackCustomEvent('com','section','expressflowloader',{event:'ExpressFlowLoaderHidden',cid:this.campaignId,domain:config.hostApi});this.eventTracker.trackCustomEvent('imp','section','registration',{event:'RegistrationSectionImpression',cid:this.campaignId,domain:config.hostApi});this.eventTracker.trackCustomEvent('imp','block','expressflowpii',{event:'ExpressFlowPII',cid:this.campaignId,domain:config.hostApi,usertype:userType,xverifyStatus:localStorage?localStorage.getItem('xverifyStatus'):null,missingFields:missingFields});if(document.querySelector('#landerform #entersweeps').style.display==='none'){document.querySelector('#landerform').setAttribute('data-pii-noemail','true');}
if(window.noDataPreprop){this.app.element('loaderSpinner').hide();this.app.element('landerPage').visible(true);}
document.body.setAttribute('data-lander','visible');window.expressCurrStepComplete='PiiShown';}else{this.loaderCheckTimeout=setTimeout(()=>{this.hideLoaderAndDisplayPII(userType,missingFields);},50);}}}
submitFLowForExpUser(resp){try{var surveyPath=(resp===null||resp===void 0?void 0:resp.submit_api)||'survey/register-user';var email_id=resp===null||resp===void 0?void 0:resp.email_id;if(this.loaderEle){var elapsedDiff=Date.now()-this.loadStart;if(elapsedDiff>this.loaderStepLimit*3){this.loaderEle.setAttribute('data-step',4);this.loaderStepComplete.push(3);}else{setTimeout(()=>{this.loaderEle.setAttribute('data-step',4);this.loaderStepComplete.push(3);},this.loaderStepLimit*3-elapsedDiff);}}
var apiPath=window.config.hostApi+"/api/"+surveyPath;if(!email_id){if(!document.querySelector('#movetonextpage')||document.querySelector('#movetonextpage').style.display==='none'){this.hideLoaderAndDisplayPII('NewUser');}else{document.querySelector('#movetonextpage').addEventListener('click',()=>{this.handleExpressCtaClick({eventName:'ExpressFlowMoveToNextPageClick',userType:'NewUser'});},{once:true});if(this.enableExpressRegAutoAction){this.twoStepCtaClickTimeout=setTimeout(()=>{this.handleExpressCtaClick({eventName:'ExpressFlowMoveToNextPageAuto',userType:'NewUser'});},this.autoRedirectTimeout);}}}else if(email_id&&surveyPath=='survey/retarget-user'){var _resp$info_req;if(!window.emailSubmited)this.loaderEle.setAttribute('data-usertype','fulldata');if(((_resp$info_req=resp.info_req)===null||_resp$info_req===void 0?void 0:_resp$info_req.length)>0){window.isPartialData=true;window.partialDataElements=resp.info_req;resp.info_req.forEach(el=>{var domElement;if(el==='stateCode'){domElement=document.querySelector('select[name="'+el+'"]');}else if(el==='userDOB'){domElement=document.querySelector('input[name="'+el+'"]');this.addResetNerrorClass(document.querySelector('select[name="dobmonth"]'));this.addResetNerrorClass(document.querySelector('select[name="dobdate"]'));this.addResetNerrorClass(document.querySelector('select[name="dobyear"]'));}else{domElement=document.querySelector('input[name="'+el+'"]');}
this.addResetNerrorClass(domElement);});var elementInput=this.app.element('input','tag').all();var elementSelect=this.app.element('select','tag').all();var elements=[];for(var i=0;i<elementInput.length;i++){elements.push(elementInput[i]);};for(var _i=0;_i<elementSelect.length;_i++){elements.push(elementSelect[_i]);};for(var ele of elements){if(["dobmonth","dobdate","dobyear","male","female","gendervalue1","cityName","stateCode"].indexOf(ele.name)==-1){if(resp.info_req.indexOf(ele.name)==-1){this.hideElandAddClass(ele);}}}
if(resp.info_req.indexOf('gender')==-1){this.hideElandAddClass(document.querySelector('#male'));this.hideElandAddClass(document.querySelector('#female'));}
if(resp.info_req.indexOf('userDOB')==-1){this.hideElandAddClass(document.querySelector('select[name="dobmonth"]'));this.hideElandAddClass(document.querySelector('select[name="dobdate"]'));this.hideElandAddClass(document.querySelector('select[name="dobyear"]'));}
if(resp.info_req.indexOf('zipcode')==-1){this.hideElandAddClass(document.querySelector('#cityName'));this.hideElandAddClass(document.querySelector('#stateCode'));}
if(!document.querySelector('#movetonextpage')||document.querySelector('#movetonextpage').style.display==='none'){this.hideLoaderAndDisplayPII('PartialUserDataMismatch',resp.info_req);}else{this.delayExpressUserFlow=0;document.querySelector('#movetonextpage').addEventListener('click',()=>{this.handleExpressCtaClick({eventName:'ExpressFlowMoveToNextPageClick',userType:'PartialUserDataMismatch',dataForShowPII:resp.info_req});},{once:true});if(this.enableExpressRegAutoAction){this.twoStepCtaClickTimeout=setTimeout(()=>{this.handleExpressCtaClick({eventName:'ExpressFlowMoveToNextPageAuto',userType:'PartialUserDataMismatch',dataForShowPII:resp.info_req});},this.autoRedirectTimeout);}}}else{if(!window.emailSubmited&&document.querySelector('#movetonextpage'))this.loaderEle.setAttribute('data-showcta','true');if(document.getElementById('updatepiidetails')&&!window.emailSubmited){document.getElementById('updatepiidetails').style.display="block";}
if(!document.querySelector('#movetonextpage')){this.expressSelectNextPage(email_id,apiPath);}else{this.delayExpressUserFlow=0;document.querySelector('#movetonextpage').addEventListener('click',()=>{this.handleExpressCtaClick({eventName:'ExpressFlowMoveToNextPageClick',userType:'DupUserFullData',dataForRedirect:{email_id,apiPath}});},{once:true});if(this.enableExpressRegAutoAction){this.twoStepCtaClickTimeout=setTimeout(()=>{this.handleExpressCtaClick({eventName:'ExpressFlowMoveToNextPageAuto',userType:'DupUserFullData',dataForRedirect:{email_id,apiPath}});},this.autoRedirectTimeout);}}}}else if(email_id&&surveyPath=='survey/register-user'){if(!resp.validated&&this.missingFields.length===0&&!window.emailSubmited){this.loaderEle.setAttribute('data-usertype','partialdata');if(!document.querySelector('#movetonextpage')||document.querySelector('#movetonextpage').style.display==='none'){if(document.getElementById('updatepiidetails')){document.getElementById('updatepiidetails').style.display="block";}
if(!document.getElementById('submituserdetials'))this.hideLoaderAndDisplayPII('NewUserPrepopOldFlow');else this.eventTracker.trackCustomEvent('imp','block','expressflowcontinueshown',{event:'ExpressFlowContinueShown',cid:this.campaignId,domain:config.hostApi,usertype:"NewUserPrepop"});}else{document.querySelector('#movetonextpage').addEventListener('click',()=>{if(document.getElementById('updatepiidetails')){document.getElementById('updatepiidetails').style.display="block";}
if(document.getElementById('submituserdetials'))this.eventTracker.trackCustomEvent('imp','block','expressflowcontinueshown',{event:'ExpressFlowContinueShown',cid:this.campaignId,domain:config.hostApi,usertype:"NewUserPrepop"});this.handleExpressCtaClick({eventName:'ExpressFlowMoveToNextPageClick',userType:'NewUserPrepop'});},{once:true});if(this.enableExpressRegAutoAction){this.twoStepCtaClickTimeout=setTimeout(()=>{if(document.getElementById('updatepiidetails')){document.getElementById('updatepiidetails').style.display="block";}
if(document.getElementById('submituserdetials'))this.eventTracker.trackCustomEvent('imp','block','expressflowcontinueshown',{event:'ExpressFlowContinueShown',cid:this.campaignId,domain:config.hostApi,usertype:"NewUserPrepop"});this.handleExpressCtaClick({eventName:'ExpressFlowMoveToNextPageAuto',userType:'NewUserPrepop'});},this.autoRedirectTimeout);}}}else{if(document.querySelector('#landerform #entersweeps')&&document.querySelector('#expressemailsubmit #entersweeps')){document.querySelector('#landerform #entersweeps').value=document.querySelector('#expressemailsubmit #entersweeps').value;this.hideElandAddClass(document.querySelector('#landerform #entersweeps'));}
if(!document.querySelector('#movetonextpage')||document.querySelector('#movetonextpage').style.display==='none'){this.hideLoaderAndDisplayPII('NewUserEmailInput');}else{document.querySelector('#movetonextpage').addEventListener('click',()=>{this.handleExpressCtaClick({eventName:'ExpressFlowMoveToNextPageClick',userType:'NewUserEmailInput'});},{once:true});if(this.enableExpressRegAutoAction){this.twoStepCtaClickTimeout=setTimeout(()=>{this.handleExpressCtaClick({eventName:'ExpressFlowMoveToNextPageAuto',userType:'NewUserEmailInput'});},this.autoRedirectTimeout);}}}}}catch(e){if(window.Sentry&&typeof window.Sentry.captureException==='function'){window.Sentry.captureException(e);}
this.hideLoaderAndDisplayPII();console.log('exp user flow submit error: ',e);}}
expressSelectNextPage(email_id,apiPath){var _window$customData8;var additionalData=arguments.length>2&&arguments[2]!==undefined?arguments[2]:{};if((_window$customData8=window.customData)!==null&&_window$customData8!==void 0&&_window$customData8.enablePushNami&&window.pushStatus&&this.enablePushNamiOverlay&&!window.pushnamiComplete&&!this.app.isIOS()){document.body.addEventListener('overlayShownComplete',()=>{this.eventTracker.trackCustomEvent('imp','section','pushoverlayprompt',{event:'pushOverlayPromptAutoRedirected',pushstatus:window.pushStatus});this.expressFlowRedirect(email_id,apiPath,additionalData);});}else{this.expressFlowRedirect(email_id,apiPath,additionalData);}}
handleExpressCtaClick(args){if(this.twoStepCtaClickTimeout)clearTimeout(this.twoStepCtaClickTimeout);var{eventName,userType,dataForShowPII,dataForRedirect,additionalData={}}=args;var{email_id,apiPath}=dataForRedirect||{};this.eventTracker.trackCustomEvent('click','section',eventName.toLowerCase(),{event:eventName,cid:this.campaignId,domain:config.hostApi,userType:userType});if(dataForRedirect)this.expressSelectNextPage(email_id,apiPath,additionalData);else this.hideLoaderAndDisplayPII(userType,dataForShowPII);}
expressFlowRedirect(email_id,apiPath,additionalData){var _this2=this;this.expressUserFlowTimeout=setTimeout(()=>{this.eventTracker.trackCustomEvent('com','section','expressflowloader',{event:'ExpressFlowLoaderHidden',cid:this.campaignId,domain:config.hostApi});window.expressCurrStepComplete='EmailSubmitFullUser';if(!window.emailSubmited&&window.noDataPreprop){this.eventTracker.trackCustomEventPromise('button','click','email-submit',{event:'EmailSubmit',error:false,autoredirecting:true}).then(_asyncToGenerator(function*(){if(window.dataLayer)window.dataLayer.push({event:'emailsubmit'});_this2.eventTracker.trackCustomEventPromise('com','section','registration',{event:'RegistrationSectionComplete',userType:'DupUserFullData'});try{yield _this2.app.checkAndFirePartnerPixel(true);console.log('postback pixel fire complete');}catch(e){console.log('postback pixel error: ',err);}
_this2.app.postApi(apiPath,_objectSpread({emailAddress:email_id,hasUserInfo:"1",next:"profile"},additionalData)).then(x=>{var res=x.response;_this2.app.redirectFunctionality(res);});}));}else{this.eventTracker.trackCustomEventPromise('com','section','expressregistration',{event:'ExpressRegistrationSectionComplete',userType:'NewUserEmailInput'});this.app.postApi(apiPath,_objectSpread({emailAddress:email_id,hasUserInfo:"1",next:"profile"},additionalData)).then(x=>{var res=x.response;this.app.redirectFunctionality(res);});}},this.delayExpressUserFlow);}
execValidateUser(checkCampainInitiate){this.validateExpressUser().then(resp=>{if(checkCampainInitiate&&this.isCampaignInitiated){if(resp!==null&&resp!==void 0&&resp.success)this.submitFLowForExpUser(resp);}else{if(checkCampainInitiate){var intervl=setInterval(()=>{if(this.isCampaignInitiated){clearInterval(intervl);if(resp!==null&&resp!==void 0&&resp.success)this.submitFLowForExpUser(resp);}},100);}else{if(resp!==null&&resp!==void 0&&resp.success)this.submitFLowForExpUser(resp);}}},err=>{console.log('error: ',err);if(window.Sentry&&typeof window.Sentry.captureException==='function'){window.Sentry.captureException(err);}});}
submitZipcode(){var _this3=this;return _asyncToGenerator(function*(){var _window7,_window7$experiment_c;_this3.app.fireCustomPixel('block-zip');_this3.app.setCustomData({customData:{zipcode:document.querySelector('#zipcode').value}});_this3.eventTracker.trackCustomEvent('click','button','zipcode',{event:'zipCodeSubmit',zipdata:document.querySelector('#zipcode').value});if(window.dataLayer){window.dataLayer.push({event:'zipCodeSubmit'});}
if((_window7=window)!==null&&_window7!==void 0&&(_window7$experiment_c=_window7.experiment_config)!==null&&_window7$experiment_c!==void 0&&_window7$experiment_c.enableArbFlow){yield _this3.app.fireDefaultHOConversionPixel();yield _this3.app.skipToNextPageJHU('lander',{event:'landerSkipped'},'linkout');}else{_this3.app.skipToNextPageJHU('lander',{event:'landerSkipped'},'linkout');}})();}
cookieGDPR(type){if(type=='accept'){localStorage.setItem('gdpr_granted','1');this.app.element('cookiepopup').hide();}else if(type=='reject'){this.deleteCookie();this.app.element('cookiepopup').hide();}}
deleteCookie(){var a=new Image();a.src=config.hostApi+"/api/delete-cookie?canary=1";}}